import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Exo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <header>
        <nav>
          <img/>
          <a href="">Home</a>
          <a href="/events">Event</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>


      <main className={styles.main}>
        <a href="">
        <img/>
        <h2>Event in London</h2>
        
          </a>
          <a href="">
        <img/>
        <h2>Event in San Fransico</h2>
        
          </a>
          <a href="">
        <img/>
        <h2>Event in Barcelona</h2>
        
          </a>
      </main>
      <footer className={styles.footer}>
        <p> @Copyright - Vitor Exo JS</p>

      </footer>
      </div>
    </>
  )
}
