import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';
import { HomePage } from '../components/home/home-page';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Exo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <header>
        <nav>
          <Link legacyBehavior href="" passHref>
          <a>Home</a>
          </Link>
          <Link legacyBehavior href="/events" passHref>
          <a>Event</a>
          </Link>
          <Link legacyBehavior href="/about-us" passHref>
          <a>About us</a>
          </Link>
        </nav>
      </header>

{/* 
      <main className={styles.main}>
        {data.map(ev => 
        <Link legacyBehavior key={ev.id} href={`/events/${ev.id}` } passHref>
        <a> 
        <Image width={200} height={200} alt={ev.title} src={ev.image}></Image> 
        <h2>{ev.title}</h2> 
        <p> {ev.description}</p> 
        </a>
        </Link>
        ) }
      </main> */}
      <HomePage data={data}/>
      <footer className={styles.footer}>
        <p> @Copyright - Vitor Exo JS</p>

      </footer>
      </div>
    </>
  )
}

export async function getServerSideProps (){ 
  const {events_categories} = await import ('../../data/data.json');

  console.log(events_categories);
  return {
      props:{
          data: events_categories
      }
  }
}